### ISSUE TITLE
How to configure the OIDC config with GO package-github.com/hashicorp/vault/api

### ISSUE THREAD

**Issue by mayankmike86** [hashicorp/hello-vault-go#38]
We are able to initialize/unseal and enable the vault using bellow code.

newres, err := client.Sys().Init(&intireq)
resseal, err := client.Sys().Unseal("xxxxxxxxxxxxxxxxxxxxx")
fmt.Println("resseal:", resseal)
enableopt := vault.MountInput{}
enableopt.Type = "oidc"
client.SetToken("xxxxxxxxxxxxxxxxxx")

err = client.Sys().EnableAuthWithOptions("oidc", &enableopt)
We can see oidc enabled in UI also. Now we need to configure the oidc, which if done from UI it is using below POST api with configs id: "oidc", oidc_discovery_url:"xxxxxx"......

https://vault.xxxxxx.com/v1/auth/oidc/config
We need to configure the same from our GO code where we are using go client vault "github.com/hashicorp/vault/api"

Not able to get the method for auth configuration need help on correct method.

**Comment by AnPucel** [comment]
Hi there! Thanks for reaching out. As this seems to be more of a question and not in our area of expertise. It might be a question better suited for our discussion forum which you can find [here](https://discuss.hashicorp.com/c/vault/).
