### ISSUE TITLE
Got an error when running the 'run.sh' for Sample-app

### ISSUE THREAD

**Issue by JimBeam2019** [hashicorp/hello-vault-go#43]
Hi Vault team,

I was trying to run the sample-app by executing the run shell script, and it was stuck at the error 'RUN go build -o hello-vault', shown as below. I was able to build the golang code without docker successfully, but it simply failed to build in docker.

Any help would be appreciated.

![Screenshot_2023-06-13_15-26-47](https://github.com/hashicorp/hello-vault-go/assets/50510995/fbe47a65-6a35-41f0-9972-6dfcceba7887)

**Comment by jyankel** [comment]
Ran into this.  Fixed by updating the Dockerfile to upgrade golang.  FROM golang:1.20-alpine AS build

**Comment by averche** [comment]
Thanks for reporting this, @jyankel! #46 should fix this :)
